### ISSUE TITLE
ElasticSearch plugin assumes custom field plugin is installed

### ISSUE THREAD

**Issue by erl4nc** [RestyaPlatform/board-apps#100]
Error log:

```
2018/05/04 09:59:02 [error] 31211#31211: *911999 FastCGI sent in stderr: "PHP message: PHP Warning:  pg_query_params(): Query failed: ERROR:  relation &quot;cards_custom_fields&quot; does not exist
LINE 1: INSERT INTO cards_custom_fields (created, modified, card_id,...
                    ^ in server/php/R/r.php on line 4528" while reading response header from upstream, client: , server: , request: "POST /api/v1/boards/26/lists/283/cards/938/copy.json?token=219d54a2c10a6501c8948e45e1f3cb4653312afd HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "", referrer: ""

2018/05/04 09:59:26 [error] 31211#31211: *911999 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Elastica\Exception\NotFoundException: doc id 940 not found in server/php/plugins/ElasticSearch/libs/vendors/Elastica/Type.php:250
Stack trace:
#0 server/php/plugins/ElasticSearch/functions.php(80): Elastica\Type->getDocument('940')
#1 server/php/R/r.php(5917): deleteCardFromElastica('940')
#2 server/php/bootstrap.php(148): r_delete('/boards/?/lists...', Array, Array)
```

**Comment by sridhar391** [comment]
FIxed in the commit https://github.com/RestyaPlatform/board/commit/645d5b57daa1a0d748b82b579c0cece62f5a10d1 and closing the issue
